export type Industry = {
  slug: string;
  name: string;
  shortName: string;
  icon: string;
  tagline: string;
  description: string;
  heroTitle: string;
  heroSubtitle: string;
  challenges: { title: string; desc: string }[];
  solutions: { title: string; desc: string }[];
  services: string[];
  results: { metric: string; label: string }[];
  faqs: { q: string; a: string }[];
  keywords: string[];
  metaTitle: string;
  metaDescription: string;
};

export const industries: Industry[] = [
  {
    slug: "tourism-hospitality",
    name: "Tourism & Hospitality",
    shortName: "Tourism",
    icon: "Plane",
    tagline: "Turn browsers into bookers",
    description: "Websites and digital marketing for Zimbabwean tourism operators, lodges, hotels, and tour companies.",
    heroTitle: "Digital Marketing for Tourism & Hospitality in Zimbabwe",
    heroSubtitle: "From Victoria Falls to Eastern Highlands — we help lodges, tour operators, and hotels get found online, take direct bookings, and reduce reliance on OTA commissions.",
    challenges: [
      { title: "Invisible on Google", desc: "Tourists search \"places to stay in Victoria Falls\" and your lodge doesn't appear. You're losing bookings to competitors with better SEO." },
      { title: "OTA commission drain", desc: "Booking.com and SafariNow take 15-25% commission on every booking. You need a direct booking website to reclaim margins." },
      { title: "No mobile booking", desc: "70%+ of tourists research on mobile. If your site isn't mobile-optimized with instant booking, you're losing them." },
      { title: "Outdated website", desc: "Your current website looks like it was built in 2010. Tourists judge quality by website quality — a poor site means lost trust." },
    ],
    solutions: [
      { title: "Direct Booking Websites", desc: "Custom websites with real-time availability, instant booking, and payment integration (Paynow, EcoCash, Stripe). No OTA commissions." },
      { title: "Tourism SEO", desc: "Rank on Page 1 for \"hotels in Harare\", \"safari Zimbabwe\", \"Victoria Falls accommodation\" and other high-intent tourism keywords." },
      { title: "WhatsApp Booking Integration", desc: "Let tourists enquire and book directly via WhatsApp Business API with automated responses and booking confirmations." },
      { title: "Instagram & Social Marketing", desc: "Visual content campaigns showcasing your property, tours, and experiences to drive direct inquiries." },
    ],
    services: ["Web Design", "SEO Services", "Social Media Marketing", "WhatsApp Integration"],
    results: [
      { metric: "15x", label: "More daily inquiries" },
      { metric: "Page 1", label: "Google ranking for tourism keywords" },
      { metric: "300%", label: "Increase in mobile bookings" },
      { metric: "0%", label: "OTA commission on direct bookings" },
    ],
    faqs: [
      { q: "How much does a tourism website cost in Zimbabwe?", a: "A professional tourism website with booking functionality costs $1,500-$5,000 depending on features. Basic lodge sites start at $1,500. Full booking systems with real-time availability and payment integration start at $3,000. KuWeX Studios has built tourism websites for Zimbabwean lodges and tour operators — see our portfolio at https://kuwexstudios.co.zw/portfolio." },
      { q: "Can you integrate online booking for my lodge or hotel?", a: "Yes. We build direct booking systems with real-time room availability, instant confirmation, and payment integration via Paynow, EcoCash, or Stripe. This eliminates OTA commissions (15-25%) and puts you in control of your guest experience. Booking systems start at $3,000." },
      { q: "How do I rank my tourism business on Google in Zimbabwe?", a: "Tourism SEO requires: a fast mobile-first website, Google Business Profile optimization, location-specific keywords (e.g., \"lodges near Victoria Falls\"), high-quality images with alt text, schema markup for reviews and ratings, and consistent content marketing. KuWeX Studios achieves Page 1 rankings for tourism clients within 3-6 months." },
      { q: "Do you work with tour operators and safari companies?", a: "Yes. We've built websites and digital marketing campaigns for Zimbabwean tour operators, safari companies, and adventure tourism businesses. We understand the Zimbabwe tourism market — from Victoria Falls to Eastern Highlands, Hwange to Mana Pools." },
    ],
    keywords: [
      "tourism website design Zimbabwe", "hotel website Zimbabwe",
      "lodge booking system Zimbabwe", "tour operator marketing Zimbabwe",
      "safari website design Zimbabwe", "Victoria Falls hotel marketing",
      "hospitality digital marketing Harare", "direct booking website Zimbabwe",
    ],
    metaTitle: "Tourism & Hospitality Digital Marketing Zimbabwe | KuWeX Studios",
    metaDescription: "Websites, SEO, and direct booking systems for Zimbabwean lodges, hotels, tour operators, and safari companies. Reduce OTA commissions, increase direct bookings. From $1,500.",
  },
  {
    slug: "real-estate",
    name: "Real Estate",
    shortName: "Real Estate",
    icon: "Home",
    tagline: "Sell properties faster online",
    description: "Property websites, listings platforms, and lead generation for Zimbabwean real estate agents and agencies.",
    heroTitle: "Digital Marketing for Real Estate in Zimbabwe",
    heroSubtitle: "Property buyers start on Google. We help Zimbabwean real estate agents and agencies rank higher, capture leads, and sell properties faster with custom websites and SEO.",
    challenges: [
      { title: "Buyers can't find you", desc: "When someone searches \"property for sale in Harare\" or \"houses for rent in Bulawayo\", your agency doesn't appear. You're invisible to ready buyers." },
      { title: "No lead capture", desc: "Your listings are on Property.co.zw but you have no way to capture leads on your own website. You're dependent on third-party platforms." },
      { title: "Outdated listings", desc: "Your current website makes it hard to add, update, or remove property listings. You need a CMS built for real estate." },
      { title: "No WhatsApp integration", desc: "Zimbabwean buyers prefer WhatsApp. If they can't enquire about a property via WhatsApp instantly, they move to the next agent." },
    ],
    solutions: [
      { title: "Property Listing Websites", desc: "Custom real estate websites with searchable listings, map views, photo galleries, and a CMS to manage properties in minutes." },
      { title: "Real Estate SEO", desc: "Rank for \"property for sale Harare\", \"land for sale Zimbabwe\", \"apartments for rent Bulawayo\" — high-intent keywords from ready buyers." },
      { title: "WhatsApp Lead Capture", desc: "Every property listing has a WhatsApp enquiry button. Capture leads instantly, respond in minutes, close more deals." },
      { title: "Google Ads for Properties", desc: "Target buyers searching for specific property types and locations. Get qualified leads within 24 hours of launching a campaign." },
    ],
    services: ["Web Design", "SEO Services", "Google Ads", "WhatsApp Integration"],
    results: [
      { metric: "3x", label: "More property inquiries" },
      { metric: "Page 1", label: "Ranking for property keywords" },
      { metric: "60%", label: "Leads via WhatsApp" },
      { metric: "48h", label: "From launch to first lead" },
    ],
    faqs: [
      { q: "How much does a real estate website cost in Zimbabwe?", a: "A professional real estate website with property listings, search functionality, and WhatsApp integration costs $2,000-$5,000. Basic agent sites start at $1,500. Full listing platforms with CMS, map search, and lead management start at $3,000. KuWeX Studios builds custom real estate websites optimized for the Zimbabwean market." },
      { q: "Can I manage my own property listings?", a: "Yes. We build real estate websites with a custom CMS that lets you add, edit, and remove property listings in minutes — no technical skills required. Upload photos, set prices, add descriptions, and publish instantly." },
      { q: "How do I rank my real estate agency on Google in Zimbabwe?", a: "Real estate SEO requires: location-specific keywords (\"property for sale Harare North\", \"land for sale Goromonzi\"), Google Business Profile optimization, fast mobile-first website, property schema markup, and consistent blog content about the Zim property market. KuWeX Studios achieves Page 1 rankings within 3-6 months." },
      { q: "Can you integrate WhatsApp enquiries for property listings?", a: "Yes. Every property listing on your website gets a WhatsApp enquiry button that opens a pre-filled message with the property details. Buyers contact you instantly. This is critical in Zimbabwe where WhatsApp is the #1 communication channel." },
    ],
    keywords: [
      "real estate website Zimbabwe", "property website design Zimbabwe",
      "real estate SEO Zimbabwe", "property listings website Harare",
      "estate agent website Zimbabwe", "property marketing Zimbabwe",
      "real estate digital marketing Harare", "property for sale website Zimbabwe",
    ],
    metaTitle: "Real Estate Website Design & Marketing Zimbabwe | KuWeX Studios",
    metaDescription: "Custom real estate websites with property listings, WhatsApp integration, and SEO for Zimbabwean agents and agencies. Sell properties faster. From $1,500.",
  },
  {
    slug: "mining",
    name: "Mining & Quarrying",
    shortName: "Mining",
    icon: "Mountain",
    tagline: "Build trust with investors",
    description: "Corporate websites and digital presence for Zimbabwean mining companies, quarry operators, and mineral traders.",
    heroTitle: "Digital Marketing for Mining Companies in Zimbabwe",
    heroSubtitle: "Mining companies need credibility online. We build professional websites that attract investors, satisfy compliance, and showcase your operations to the global market.",
    challenges: [
      { title: "No online credibility", desc: "Investors and partners Google your company before doing business. No website or a poor one means lost deals and missed partnerships." },
      { title: "Compliance requirements", desc: "Government, EMA, and international buyers require documentation and transparency. A professional website demonstrates compliance and builds trust." },
      { title: "Investor relations", desc: "You need a platform to share reports, licenses, and operational updates with investors and stakeholders in a professional manner." },
      { title: "Talent attraction", desc: "Skilled mining professionals research companies online. A strong digital presence helps you attract engineers, geologists, and operators." },
    ],
    solutions: [
      { title: "Corporate Mining Websites", desc: "Professional, multi-page websites showcasing your operations, licenses, team, safety record, and mineral portfolio. Built for investor confidence." },
      { title: "Investor Relations Portals", desc: "Secure sections for sharing reports, financials, and operational updates with investors and board members." },
      { title: "SEO for Mining Sector", desc: "Rank for \"mining companies Zimbabwe\", \"gold mining Zimbabwe\", \"chrome miners\" — keywords that investors and buyers search." },
      { title: "Document Management", desc: "Upload and organize licenses, EMA certificates, compliance documents, and operational reports in a structured, professional format." },
    ],
    services: ["Web Design", "SEO Services", "Software Development", "Branding"],
    results: [
      { metric: "2x", label: "Investor inquiries" },
      { metric: "Page 1", label: "Ranking for mining keywords" },
      { metric: "100%", label: "Compliance documentation online" },
      { metric: "24/7", label: "Investor access to reports" },
    ],
    faqs: [
      { q: "How much does a mining company website cost in Zimbabwe?", a: "A professional corporate mining website costs $2,500-$8,000 depending on features. Standard corporate sites with operations overview, team, and contact start at $2,500. Sites with investor portals, document management, and compliance sections start at $5,000. KuWeX Studios understands the Zimbabwean mining sector." },
      { q: "Can you build an investor relations portal?", a: "Yes. We build secure investor portals where you can share financial reports, operational updates, licenses, and compliance documents with authorized investors and stakeholders. Access can be password-protected with role-based permissions." },
      { q: "How do I rank my mining company on Google?", a: "Mining SEO requires: keyword targeting (\"mining companies Zimbabwe\", \"gold mining Harare\"), Google Business Profile, professional website with operations content, schema markup, and industry-specific backlinks. KuWeX Studios helps mining companies build online credibility within 3-6 months." },
      { q: "Do you understand Zimbabwe's mining sector?", a: "Yes. We've worked with companies in construction, engineering, and energy sectors in Zimbabwe. We understand the regulatory landscape (EMA, MMCZ, Ministry of Mines), the investor audience, and the compliance requirements for Zimbabwean mining operations." },
    ],
    keywords: [
      "mining company website Zimbabwe", "mining website design Zimbabwe",
      "mining SEO Zimbabwe", "corporate website mining Harare",
      "investor relations website Zimbabwe", "mining digital marketing Zimbabwe",
      "gold mining website Zimbabwe", "chrome mining Zimbabwe website",
    ],
    metaTitle: "Mining Company Website Design & Marketing Zimbabwe | KuWeX Studios",
    metaDescription: "Corporate websites, investor portals, and SEO for Zimbabwean mining companies. Build credibility with investors and buyers. From $2,500.",
  },
  {
    slug: "agriculture",
    name: "Agriculture & Farming",
    shortName: "Agriculture",
    icon: "Wheat",
    tagline: "Grow your agribusiness online",
    description: "Websites and digital marketing for Zimbabwean farmers, agribusinesses, agricultural suppliers, and cooperatives.",
    heroTitle: "Digital Marketing for Agriculture & Farming in Zimbabwe",
    heroSubtitle: "From tobacco farmers in Mashonaland to horticulture exporters in Mazowe — we help agribusinesses reach buyers, suppliers, and partners online.",
    challenges: [
      { title: "Buyers can't find you", desc: "International buyers search \"agricultural suppliers Zimbabwe\" and you don't appear. You're losing export opportunities to competitors with websites." },
      { title: "No online catalog", desc: "Your products (seeds, fertilizer, equipment, produce) aren't online. Buyers want to browse before contacting." },
      { title: "Seasonal marketing gaps", desc: "You market during harvest season but have no online presence year-round to build relationships with buyers." },
      { title: "Cooperative communication", desc: "Your farmer cooperative or association needs a platform to share information, prices, and updates with members." },
    ],
    solutions: [
      { title: "Agribusiness Websites", desc: "Professional websites showcasing your products, certifications, farming practices, and supply capacity. Built for local and international buyers." },
      { title: "Product Catalogs", desc: "Online catalogs for seeds, fertilizer, equipment, or produce with specifications, pricing, and WhatsApp enquiry buttons." },
      { title: "Agriculture SEO", desc: "Rank for \"agricultural suppliers Zimbabwe\", \"farming equipment Harare\", \"tobacco farmers Zimbabwe\" — keywords buyers actually search." },
      { title: "WhatsApp Order Integration", desc: "Let buyers place orders, request quotes, and get product information via WhatsApp — the channel Zimbabwean buyers prefer." },
    ],
    services: ["Web Design", "SEO Services", "Social Media Marketing", "WhatsApp Integration"],
    results: [
      { metric: "4x", label: "Buyer inquiries" },
      { metric: "Page 1", label: "Ranking for agriculture keywords" },
      { metric: "50%", label: "Orders via WhatsApp" },
      { metric: "24/7", label: "Product catalog availability" },
    ],
    faqs: [
      { q: "How much does an agriculture website cost in Zimbabwe?", a: "An agribusiness website costs $1,500-$5,000. Basic farm or supplier sites start at $1,500. Sites with product catalogs, WhatsApp ordering, and SEO start at $3,000. KuWeX Studios builds websites tailored to Zimbabwean agriculture — from tobacco to horticulture to livestock." },
      { q: "Can you build an online product catalog for my agribusiness?", a: "Yes. We build online catalogs with product photos, specifications, pricing, and WhatsApp enquiry buttons. Buyers can browse your products 24/7 and contact you instantly. Catalogs can be managed via a simple CMS — no technical skills needed." },
      { q: "How do I rank my agribusiness on Google in Zimbabwe?", a: "Agriculture SEO requires: product-specific keywords (\"agricultural seeds Zimbabwe\", \"farming equipment Harare\"), Google Business Profile, fast website with product pages, schema markup, and content about Zimbabwean farming practices. KuWeX Studios achieves Page 1 rankings within 3-6 months." },
      { q: "Do you work with farmer cooperatives and associations?", a: "Yes. We build websites and platforms for farmer cooperatives and agricultural associations — including member directories, price information boards, event calendars, and communication tools. These platforms help cooperatives serve their members more effectively." },
    ],
    keywords: [
      "agriculture website Zimbabwe", "farming website design Zimbabwe",
      "agribusiness digital marketing Zimbabwe", "agricultural suppliers website Harare",
      "tobacco farming website Zimbabwe", "horticulture website Zimbabwe",
      "farm equipment website Zimbabwe", "agriculture SEO Zimbabwe",
    ],
    metaTitle: "Agriculture & Farming Website Design Zimbabwe | KuWeX Studios",
    metaDescription: "Websites, product catalogs, and SEO for Zimbabwean farmers, agribusinesses, and agricultural suppliers. Reach buyers online. From $1,500.",
  },
  {
    slug: "healthcare",
    name: "Healthcare & Medical",
    shortName: "Healthcare",
    icon: "HeartPulse",
    tagline: "Connect with patients online",
    description: "Websites and digital marketing for Zimbabwean clinics, medical practices, pharmacies, and healthcare providers.",
    heroTitle: "Digital Marketing for Healthcare & Medical in Zimbabwe",
    heroSubtitle: "Patients search for healthcare providers online. We help clinics, doctors, pharmacies, and medical practices get found, build trust, and streamline patient communication.",
    challenges: [
      { title: "Patients can't find you", desc: "When patients search \"clinic in Harare\" or \"doctor near me\", your practice doesn't appear. You're losing patients to competitors with better online visibility." },
      { title: "No appointment booking", desc: "Patients call during business hours and get no answer. You need online appointment booking to capture patients 24/7." },
      { title: "Trust and credibility", desc: "Patients research healthcare providers online before choosing. No website or a poor one means lost trust and lost patients." },
      { title: "No patient communication channel", desc: "Patients have questions but can't reach you easily. WhatsApp integration lets them ask questions and book appointments instantly." },
    ],
    solutions: [
      { title: "Medical Practice Websites", desc: "Professional websites for clinics, doctors, and pharmacies with services, team profiles, opening hours, and patient resources." },
      { title: "Online Appointment Booking", desc: "Let patients book appointments online 24/7. Reduce no-shows with automated WhatsApp/SMS reminders." },
      { title: "Healthcare SEO", desc: "Rank for \"clinic Harare\", \"pharmacy Zimbabwe\", \"dentist Bulawayo\" — keywords patients search when they need care." },
      { title: "WhatsApp Patient Communication", desc: "Patients can enquire about services, book appointments, and get directions via WhatsApp — the channel Zimbabweans prefer." },
    ],
    services: ["Web Design", "SEO Services", "WhatsApp Integration", "Software Development"],
    results: [
      { metric: "3x", label: "Appointment requests" },
      { metric: "Page 1", label: "Ranking for healthcare keywords" },
      { metric: "70%", label: "Bookings via WhatsApp" },
      { metric: "24/7", label: "Online appointment availability" },
    ],
    faqs: [
      { q: "How much does a medical practice website cost in Zimbabwe?", a: "A healthcare website costs $1,500-$5,000. Basic clinic sites start at $1,500. Sites with online appointment booking, patient portal, and WhatsApp integration start at $3,000. KuWeX Studios builds HIPAA-aware websites for Zimbabwean healthcare providers." },
      { q: "Can you add online appointment booking to my clinic website?", a: "Yes. We build online appointment booking systems where patients select a service, choose a date/time, and get instant confirmation. Automated WhatsApp reminders reduce no-shows. The booking system integrates with your existing schedule." },
      { q: "How do I rank my clinic or pharmacy on Google in Zimbabwe?", a: "Healthcare SEO requires: location-specific keywords (\"clinic Avondale Harare\", \"pharmacy Borrowdale\"), Google Business Profile optimization, fast mobile website, services pages with schema markup, and patient reviews. KuWeX Studios achieves Page 1 rankings for healthcare clients within 3-6 months." },
      { q: "Can patients book appointments via WhatsApp?", a: "Yes. We integrate WhatsApp Business API so patients can book appointments, ask about services, get directions, and receive reminders — all through WhatsApp. This is critical in Zimbabwe where WhatsApp is the primary communication channel." },
    ],
    keywords: [
      "healthcare website Zimbabwe", "clinic website design Zimbabwe",
      "medical practice website Harare", "pharmacy website Zimbabwe",
      "doctor website design Zimbabwe", "healthcare SEO Zimbabwe",
      "hospital website Zimbabwe", "medical digital marketing Harare",
    ],
    metaTitle: "Healthcare & Medical Website Design Zimbabwe | KuWeX Studios",
    metaDescription: "Websites, appointment booking, and SEO for Zimbabwean clinics, doctors, pharmacies, and healthcare providers. Connect with patients online. From $1,500.",
  },
  {
    slug: "retail-ecommerce",
    name: "Retail & E-commerce",
    shortName: "Retail",
    icon: "ShoppingCart",
    tagline: "Sell online, deliver locally",
    description: "E-commerce websites and digital marketing for Zimbabwean retailers, shops, and online stores.",
    heroTitle: "E-commerce & Retail Digital Marketing in Zimbabwe",
    heroSubtitle: "From boutiques in Harare to hardware stores in Mutare — we build online stores that sell. Paynow, EcoCash, and WhatsApp ordering built in.",
    challenges: [
      { title: "No online store", desc: "Your competitors are selling on WhatsApp and Facebook Marketplace while you have no e-commerce presence. You're losing sales daily." },
      { title: "Payment integration", desc: "You need EcoCash, Paynow, and USD payment options. Most website builders don't understand Zimbabwean payment gateways." },
      { title: "Inventory management", desc: "You can't track stock across physical shop and online store. You need a system that syncs inventory in real-time." },
      { title: "Delivery logistics", desc: "Harare and Bulawayo customers expect fast delivery. You need a website that handles delivery zones, costs, and tracking." },
    ],
    solutions: [
      { title: "E-commerce Websites", desc: "Full online stores with product catalogs, shopping cart, checkout, and payment integration (Paynow, EcoCash, Stripe, USD bank transfer)." },
      { title: "WhatsApp Commerce", desc: "Turn WhatsApp into a sales channel. Product catalogs, automated replies, order processing, and payment links — all via WhatsApp Business API." },
      { title: "Retail SEO", desc: "Rank for \"buy [product] Zimbabwe\", \"online shop Harare\", \"best price [product]\" — keywords with high purchase intent." },
      { title: "Inventory Sync", desc: "Real-time inventory management that syncs across your physical shop and online store. Never oversell or disappoint customers." },
    ],
    services: ["Web Design", "SEO Services", "Software Development", "Social Media Marketing"],
    results: [
      { metric: "10K+", label: "Monthly transactions" },
      { metric: "99.9%", label: "Platform uptime" },
      { metric: "2s", label: "Average page load" },
      { metric: "3", label: "Payment methods integrated" },
    ],
    faqs: [
      { q: "How much does an e-commerce website cost in Zimbabwe?", a: "An e-commerce website costs $2,500-$10,000 depending on features. Basic online stores with 50-100 products and Paynow integration start at $2,500. Full e-commerce platforms with inventory sync, delivery management, and WhatsApp commerce start at $5,000. KuWeX Studios has built e-commerce platforms processing 10,000+ monthly transactions." },
      { q: "Can you integrate EcoCash and Paynow payments?", a: "Yes. We integrate Paynow (supports EcoCash, OneMoney, Visa/Mastercard), Smile & Pay (ZB Bank), and direct USD bank transfers. We've built payment integrations for Zimbabwean e-commerce platforms and understand the local payment landscape." },
      { q: "Can I manage my own products and inventory?", a: "Yes. We build e-commerce websites with a user-friendly admin dashboard where you can add products, manage inventory, process orders, and view sales reports — no technical skills required. The system syncs inventory in real-time across your online and physical store." },
      { q: "How do I rank my online shop on Google in Zimbabwe?", a: "E-commerce SEO requires: product-specific keywords (\"buy iPhone Harare\", \"best price cement Zimbabwe\"), fast page load, product schema markup, Google Shopping integration, and category pages optimized for search. KuWeX Studios achieves Page 1 rankings for e-commerce clients within 3-6 months." },
    ],
    keywords: [
      "e-commerce website Zimbabwe", "online shop website Zimbabwe",
      "retail website design Harare", "EcoCash payment website Zimbabwe",
      "Paynow integration Zimbabwe", "online store Zimbabwe",
      "e-commerce development Zimbabwe", "WhatsApp commerce Zimbabwe",
    ],
    metaTitle: "E-commerce & Retail Website Design Zimbabwe | KuWeX Studios",
    metaDescription: "Online stores with Paynow, EcoCash, and WhatsApp integration for Zimbabwean retailers. Sell online and deliver locally. From $2,500.",
  },
  {
    slug: "construction-engineering",
    name: "Construction & Engineering",
    shortName: "Construction",
    icon: "HardHat",
    tagline: "Win bigger contracts",
    description: "Corporate websites and digital marketing for Zimbabwean construction companies, engineers, architects, and contractors.",
    heroTitle: "Digital Marketing for Construction & Engineering in Zimbabwe",
    heroSubtitle: "From Harare builders to civil engineers in Bulawayo — we build websites that showcase your projects, win tenders, and attract corporate clients.",
    challenges: [
      { title: "Losing tenders", desc: "Tender committees research companies online. No website means you look less credible than competitors — and lose contracts." },
      { title: "No project portfolio", desc: "Your best work is invisible. You need a professional portfolio showcasing completed projects with photos and specifications." },
      { title: "No corporate credibility", desc: "Corporate clients and government departments expect a professional website. A Facebook page doesn't build trust for million-dollar contracts." },
      { title: "Manual document sharing", desc: "You email compliance docs, CSD reports, and project plans manually. A website with a document portal streamlines everything." },
    ],
    solutions: [
      { title: "Corporate Construction Websites", desc: "Professional websites showcasing your projects, team, certifications, safety record, and capabilities. Built to win tenders." },
      { title: "Project Portfolio Galleries", desc: "Visual galleries of completed projects with descriptions, locations, project value, and client testimonials." },
      { title: "Construction SEO", desc: "Rank for \"construction companies Zimbabwe\", \"civil engineering harare\", \"building contractors Bulawayo\" — keywords clients search." },
      { title: "Tender Document Portal", desc: "Secure section for uploading and sharing compliance documents, CSD reports, and project plans with clients and tender committees." },
    ],
    services: ["Web Design", "SEO Services", "Branding", "Software Development"],
    results: [
      { metric: "400%", label: "Organic traffic growth" },
      { metric: "Page 1", label: "Ranking for construction keywords" },
      { metric: "2x", label: "Tender shortlisting rate" },
      { metric: "24/7", label: "Portfolio availability" },
    ],
    faqs: [
      { q: "How much does a construction company website cost in Zimbabwe?", a: "A professional construction website costs $2,000-$6,000. Standard corporate sites with project portfolio start at $2,000. Sites with tender document portals, project management features, and SEO start at $4,000. KuWeX Studios has built websites for Zimbabwean construction and engineering companies." },
      { q: "Can you build a project portfolio gallery?", a: "Yes. We build visual project galleries with before/after photos, project descriptions, locations, client names, and project values. You can add new projects via a simple CMS — no technical skills needed." },
      { q: "How do I rank my construction company on Google in Zimbabwe?", a: "Construction SEO requires: service-specific keywords (\"building contractors Harare\", \"civil engineering Zimbabwe\"), Google Business Profile, project portfolio pages, schema markup, and content about Zimbabwean construction trends. KuWeX Studios achieved 400% organic traffic growth for a construction client." },
      { q: "Do you understand the Zimbabwean construction sector?", a: "Yes. We've built websites for construction companies, engineering firms, and solar/energy companies in Zimbabwe. We understand the tender process, CSD compliance, and what corporate clients look for when evaluating contractors online." },
    ],
    keywords: [
      "construction company website Zimbabwe", "building contractor website Harare",
      "engineering company website Zimbabwe", "construction SEO Zimbabwe",
      "civil engineering website Zimbabwe", "construction digital marketing Harare",
      "architect website Zimbabwe", "tender portal website Zimbabwe",
    ],
    metaTitle: "Construction & Engineering Website Design Zimbabwe | KuWeX Studios",
    metaDescription: "Corporate websites, project portfolios, and SEO for Zimbabwean construction companies, engineers, and contractors. Win more tenders. From $2,000.",
  },
  {
    slug: "education",
    name: "Education & Training",
    shortName: "Education",
    icon: "GraduationCap",
    tagline: "Enroll more students online",
    description: "Websites and digital marketing for Zimbabwean schools, colleges, universities, training providers, and e-learning platforms.",
    heroTitle: "Digital Marketing for Education & Training in Zimbabwe",
    heroSubtitle: "From private colleges in Harare to online course providers — we build websites that enroll students, showcase programs, and streamline admissions.",
    challenges: [
      { title: "Students can't find you", desc: "Prospective students search \"colleges in Harare\" or \"online courses Zimbabwe\" and your institution doesn't appear. You're losing enrollments." },
      { title: "No online enrollment", desc: "Students have to visit in person to enroll. You need online application forms and course information available 24/7." },
      { title: "Outdated website", desc: "Your current website is hard to update. Course information is outdated, and staff can't add new programs easily." },
      { title: "No student communication", desc: "Students and parents have questions but can't reach you easily. WhatsApp integration lets them enquire instantly." },
    ],
    solutions: [
      { title: "Education Websites", desc: "Professional websites for schools, colleges, and training providers with course catalogs, faculty profiles, and online enrollment." },
      { title: "Online Enrollment Systems", desc: "Application forms, document uploads, payment integration for fees, and automated confirmation via WhatsApp/email." },
      { title: "Education SEO", desc: "Rank for \"colleges in Harare\", \"online courses Zimbabwe\", \"short courses Bulawayo\" — keywords students search." },
      { title: "E-learning Platforms", desc: "Custom e-learning platforms with course delivery, student dashboards, progress tracking, and certificate generation." },
    ],
    services: ["Web Design", "SEO Services", "Software Development", "Social Media Marketing"],
    results: [
      { metric: "3x", label: "Online enrollments" },
      { metric: "Page 1", label: "Ranking for education keywords" },
      { metric: "80%", label: "Applications via website" },
      { metric: "24/7", label: "Course information access" },
    ],
    faqs: [
      { q: "How much does a school or college website cost in Zimbabwe?", a: "An education website costs $2,000-$8,000. Standard college sites with course catalog start at $2,000. Sites with online enrollment, e-learning platform, and payment integration start at $5,000. KuWeX Studios builds education websites tailored to the Zimbabwean market." },
      { q: "Can you build an online enrollment system?", a: "Yes. We build online enrollment systems with application forms, document upload, course selection, fee payment (Paynow/EcoCash), and automated confirmation via WhatsApp and email. Staff can review and manage applications via an admin dashboard." },
      { q: "Can you build an e-learning platform?", a: "Yes. We build custom e-learning platforms with video course delivery, student dashboards, progress tracking, quizzes, certificate generation, and payment integration. Platforms are mobile-optimized for Zimbabwe's mobile-first students." },
      { q: "How do I rank my college on Google in Zimbabwe?", a: "Education SEO requires: course-specific keywords (\"accounting courses Harare\", \"IT training Zimbabwe\"), Google Business Profile, fast mobile website, course pages with schema markup, and student reviews. KuWeX Studios achieves Page 1 rankings within 3-6 months." },
    ],
    keywords: [
      "school website Zimbabwe", "college website design Zimbabwe",
      "university website Harare", "education website Zimbabwe",
      "e-learning platform Zimbabwe", "online courses website Zimbabwe",
      "education SEO Zimbabwe", "training provider website Harare",
    ],
    metaTitle: "Education & Training Website Design Zimbabwe | KuWeX Studios",
    metaDescription: "Websites, online enrollment, and e-learning platforms for Zimbabwean schools, colleges, and training providers. Enroll more students. From $2,000.",
  },
  {
    slug: "financial-services",
    name: "Financial Services & Fintech",
    shortName: "Finance",
    icon: "Landmark",
    tagline: "Build digital trust",
    description: "Websites and digital platforms for Zimbabwean banks, microfinance, insurance, fintech startups, and SACCOs.",
    heroTitle: "Digital Marketing for Financial Services in Zimbabwe",
    heroSubtitle: "From microfinance in Harare to fintech startups — we build secure, compliant websites that build trust with clients and regulators.",
    challenges: [
      { title: "Trust deficit online", desc: "Financial services require trust. A poor website or no website makes clients skeptical. You need a professional, secure digital presence." },
      { title: "Regulatory compliance", desc: "RBZ and SECZ requirements demand clear disclaimers, terms, and data protection. Your website must be compliant." },
      { title: "No online applications", desc: "Clients must visit in person for loans, accounts, or insurance. Online application forms would dramatically increase conversions." },
      { title: "Data security concerns", desc: "Financial data is sensitive. You need SSL, secure forms, and compliance with the Zimbabwe Data Protection Act." },
    ],
    solutions: [
      { title: "Financial Services Websites", desc: "Professional, secure websites for banks, microfinance, insurance, and fintech with services, rates, calculators, and compliance pages." },
      { title: "Online Application Forms", desc: "Secure loan, account, and insurance application forms with document upload and encrypted data transmission." },
      { title: "Financial SEO", desc: "Rank for \"microfinance Zimbabwe\", \"insurance Harare\", \"personal loan Zimbabwe\" — keywords with high commercial intent." },
      { title: "Financial Calculators", desc: "Loan calculators, insurance premium estimators, and savings calculators that engage users and generate leads." },
    ],
    services: ["Web Design", "SEO Services", "Software Development", "Branding"],
    results: [
      { metric: "4x", label: "Online applications" },
      { metric: "Page 1", label: "Ranking for finance keywords" },
      { metric: "100%", label: "Data protection compliant" },
      { metric: "24/7", label: "Application availability" },
    ],
    faqs: [
      { q: "How much does a financial services website cost in Zimbabwe?", a: "A financial services website costs $3,000-$10,000. Standard sites with services, rates, and compliance pages start at $3,000. Sites with online applications, calculators, and secure client portals start at $5,000. KuWeX Studios builds secure, compliant websites for Zimbabwean financial institutions." },
      { q: "Can you build online loan or insurance application forms?", a: "Yes. We build secure online application forms with document upload, encrypted data transmission, and automated confirmation. Staff can review applications via an admin dashboard. All forms are SSL-secured and compliant with the Zimbabwe Data Protection Act." },
      { q: "Can you build financial calculators?", a: "Yes. We build loan calculators, insurance premium estimators, savings calculators, and mortgage calculators. These tools engage users, generate leads, and improve SEO. Calculators can be customized to your specific products and rates." },
      { q: "How do you ensure data security for financial websites?", a: "We implement SSL encryption, secure form submissions, role-based access control, regular security updates, and compliance with the Zimbabwe Data Protection Act. We also provide security monitoring and backup services. Financial data is never stored in plaintext." },
    ],
    keywords: [
      "financial services website Zimbabwe", "bank website Zimbabwe",
      "microfinance website Harare", "insurance website Zimbabwe",
      "fintech website design Zimbabwe", "financial SEO Zimbabwe",
      "loan application website Zimbabwe", "SACCO website Zimbabwe",
    ],
    metaTitle: "Financial Services & Fintech Website Design Zimbabwe | KuWeX Studios",
    metaDescription: "Secure, compliant websites and online application systems for Zimbabwean banks, microfinance, insurance, and fintech. From $3,000.",
  },
  {
    slug: "legal-services",
    name: "Legal Services",
    shortName: "Legal",
    icon: "Scale",
    tagline: "Authority and credibility online",
    description: "Websites and digital marketing for Zimbabwean law firms, advocates, notaries, and legal consultants.",
    heroTitle: "Digital Marketing for Legal Services in Zimbabwe",
    heroSubtitle: "Clients research lawyers online before choosing. We build professional websites for law firms that establish authority, build trust, and generate client inquiries.",
    challenges: [
      { title: "No online authority", desc: "Potential clients search \"lawyer Harare\" or \"attorney Zimbabwe\" and your firm doesn't appear. You're losing clients to firms with better online presence." },
      { title: "No practice area pages", desc: "Clients search for specific services: \"divorce lawyer\", \"commercial attorney\", \"property lawyer\". Without dedicated practice area pages, you miss these searches." },
      { title: "Outdated or no website", desc: "Your firm's credibility is questioned when you have no website or an outdated one. Legal clients expect professionalism online." },
      { title: "No client intake", desc: "Clients call during business hours and get voicemail. Online consultation booking would capture leads 24/7." },
    ],
    solutions: [
      { title: "Law Firm Websites", desc: "Professional websites with attorney profiles, practice areas, case results, publications, and contact information." },
      { title: "Online Consultation Booking", desc: "Let clients book consultations online. Automated WhatsApp/email confirmations reduce no-shows and improve client experience." },
      { title: "Legal SEO", desc: "Rank for \"lawyer Harare\", \"attorney Zimbabwe\", \"commercial lawyer Bulawayo\" — keywords with high commercial intent." },
      { title: "Legal Content Marketing", desc: "Blog posts and articles on Zimbabwean law topics that demonstrate expertise and attract search traffic." },
    ],
    services: ["Web Design", "SEO Services", "Branding", "Social Media Marketing"],
    results: [
      { metric: "3x", label: "Consultation requests" },
      { metric: "Page 1", label: "Ranking for legal keywords" },
      { metric: "90%", label: "Client research online first" },
      { metric: "24/7", label: "Consultation booking access" },
    ],
    faqs: [
      { q: "How much does a law firm website cost in Zimbabwe?", a: "A professional law firm website costs $2,000-$6,000. Standard sites with attorney profiles and practice areas start at $2,000. Sites with online consultation booking, blog/CMS, and SEO start at $4,000. KuWeX Studios builds professional websites for Zimbabwean legal practitioners." },
      { q: "Can you add online consultation booking?", a: "Yes. We build online consultation booking systems where clients select a practice area, choose a date/time, and get instant confirmation via WhatsApp and email. Staff can manage bookings via an admin dashboard." },
      { q: "How do I rank my law firm on Google in Zimbabwe?", a: "Legal SEO requires: practice-area-specific keywords (\"commercial lawyer Harare\", \"divorce attorney Zimbabwe\"), Google Business Profile, attorney profile pages, schema markup, and legal content marketing. KuWeX Studios achieves Page 1 rankings within 3-6 months." },
      { q: "Can you write legal content for my blog?", a: "We can build the blog infrastructure and optimize it for SEO. For legal content, we recommend your attorneys write articles — we handle the SEO structure, formatting, and optimization. This ensures accuracy while maximizing search visibility." },
    ],
    keywords: [
      "law firm website Zimbabwe", "lawyer website design Zimbabwe",
      "attorney website Harare", "legal services website Zimbabwe",
      "law firm SEO Zimbabwe", "legal digital marketing Harare",
      "notary website Zimbabwe", "advocate website Zimbabwe",
    ],
    metaTitle: "Legal Services Website Design Zimbabwe | KuWeX Studios",
    metaDescription: "Professional websites, consultation booking, and SEO for Zimbabwean law firms, advocates, and legal consultants. From $2,000.",
  },
  {
    slug: "manufacturing",
    name: "Manufacturing",
    shortName: "Manufacturing",
    icon: "Factory",
    tagline: "Showcase your production power",
    description: "Corporate websites and digital marketing for Zimbabwean manufacturers, factories, and industrial companies.",
    heroTitle: "Digital Marketing for Manufacturing Companies in Zimbabwe",
    heroSubtitle: "From food processing in Harare to textile manufacturing in Bulawayo — we build websites that showcase your production capabilities and attract B2B buyers.",
    challenges: [
      { title: "Invisible to B2B buyers", desc: "Procurement managers search for suppliers online. No website means you're invisible to corporate buyers and distributors." },
      { title: "No product catalog", desc: "Your products aren't online. B2B buyers want to see specifications, certifications, and production capacity before requesting a quote." },
      { title: "No lead generation", desc: "You rely on trade shows and referrals. A website with quote forms and WhatsApp integration would generate leads 24/7." },
      { title: "Outdated brand image", desc: "Your website doesn't reflect your modern manufacturing capabilities. A professional site upgrades your brand instantly." },
    ],
    solutions: [
      { title: "Manufacturing Websites", desc: "Corporate websites showcasing your production facilities, product lines, certifications, and capacity. Built for B2B buyers." },
      { title: "Product Catalogs", desc: "Online catalogs with product specifications, datasheets, certifications, and quote request buttons." },
      { title: "Manufacturing SEO", desc: "Rank for \"manufacturers Zimbabwe\", \"food processing Harare\", \"industrial supplies Zimbabwe\" — B2B keywords." },
      { title: "B2B Lead Generation", desc: "Quote request forms, WhatsApp enquiry buttons, and lead capture tools that convert website visitors into sales leads." },
    ],
    services: ["Web Design", "SEO Services", "Software Development", "Branding"],
    results: [
      { metric: "3x", label: "B2B inquiries" },
      { metric: "Page 1", label: "Ranking for manufacturing keywords" },
      { metric: "24/7", label: "Product catalog access" },
      { metric: "2x", label: "Quote requests" },
    ],
    faqs: [
      { q: "How much does a manufacturing company website cost in Zimbabwe?", a: "A manufacturing website costs $2,500-$8,000. Standard corporate sites with product overview start at $2,500. Sites with full product catalogs, quote forms, and B2B lead generation start at $5,000. KuWeX Studios builds websites for Zimbabwean manufacturers." },
      { q: "Can you build a B2B product catalog?", a: "Yes. We build online product catalogs with specifications, datasheets, certifications, photos, and quote request buttons. Catalogs are managed via a simple CMS and optimized for SEO to attract B2B search traffic." },
      { q: "How do I rank my manufacturing company on Google?", a: "Manufacturing SEO requires: product-specific keywords (\"food processing Zimbabwe\", \"steel fabrication Harare\"), Google Business Profile, product pages with schema markup, and B2B content marketing. KuWeX Studios achieves Page 1 rankings within 3-6 months." },
      { q: "Can you integrate quote request forms?", a: "Yes. We build quote request forms where buyers specify product, quantity, and delivery requirements. Quotes are routed to your sales team via email and WhatsApp. This captures B2B leads 24/7 without manual phone handling." },
    ],
    keywords: [
      "manufacturing website Zimbabwe", "factory website design Zimbabwe",
      "industrial website Harare", "manufacturer SEO Zimbabwe",
      "product catalog website Zimbabwe", "B2B website Zimbabwe",
      "manufacturing digital marketing Harare", "industrial company website Zimbabwe",
    ],
    metaTitle: "Manufacturing Website Design Zimbabwe | KuWeX Studios",
    metaDescription: "Corporate websites, product catalogs, and B2B lead generation for Zimbabwean manufacturers. Attract corporate buyers. From $2,500.",
  },
  {
    slug: "ngos-nonprofits",
    name: "NGOs & Non-profits",
    shortName: "NGOs",
    icon: "HeartHandshake",
    tagline: "Amplify your impact online",
    description: "Websites and digital marketing for Zimbabwean NGOs, non-profits, charities, and community organizations.",
    heroTitle: "Digital Marketing for NGOs & Non-profits in Zimbabwe",
    heroSubtitle: "From Harare-based charities to community organizations across Zimbabwe — we build websites that tell your story, attract donors, and engage beneficiaries.",
    challenges: [
      { title: "Donor visibility gap", desc: "International donors research organizations online before funding. No website means lost funding opportunities." },
      { title: "No online donations", desc: "You can't accept donations online. Donors want to give via card, PayPal, or bank transfer — instantly and securely." },
      { title: "Storytelling deficit", desc: "Your impact stories aren't visible online. You need a platform to showcase projects, beneficiaries, and results." },
      { title: "No volunteer recruitment", desc: "Volunteers and partners can't find information about your work or how to get involved. An online presence solves this." },
    ],
    solutions: [
      { title: "NGO Websites", desc: "Professional websites with mission, projects, impact stories, team, donor recognition, and volunteer information." },
      { title: "Online Donation Systems", desc: "Secure donation forms accepting PayPal, Stripe, USD bank transfer, and EcoCash. Recurring donation options for sustained funding." },
      { title: "Impact Storytelling", desc: "Visual project galleries, beneficiary stories, and annual reports that demonstrate impact to donors and partners." },
      { title: "NGO SEO", desc: "Rank for your cause-specific keywords and attract organic traffic from donors, volunteers, and beneficiaries searching for your services." },
    ],
    services: ["Web Design", "SEO Services", "Social Media Marketing", "Branding"],
    results: [
      { metric: "3x", label: "Donor inquiries" },
      { metric: "2x", label: "Online donations" },
      { metric: "Page 1", label: "Ranking for cause keywords" },
      { metric: "24/7", label: "Donation availability" },
    ],
    faqs: [
      { q: "How much does an NGO website cost in Zimbabwe?", a: "An NGO website costs $1,500-$6,000. Standard sites with mission, projects, and contact start at $1,500. Sites with online donation systems, project galleries, and volunteer portals start at $3,500. KuWeX Studios offers discounted rates for registered Zimbabwean non-profits." },
      { q: "Can you build an online donation system?", a: "Yes. We build secure donation forms accepting PayPal, Stripe (international cards), USD bank transfer, and EcoCash. Features include one-time and recurring donations, donor receipts, and a donor management dashboard." },
      { q: "Do you offer discounts for NGOs and non-profits?", a: "Yes. KuWeX Studios offers 15-25% discounts for registered Zimbabwean non-profits and community organizations. We understand the budget constraints of the NGO sector and work to deliver maximum impact within your budget." },
      { q: "Can you help with social media marketing for our NGO?", a: "Yes. We manage social media campaigns for NGOs — including Facebook, Instagram, and WhatsApp Channel management. We create content that tells your impact story, engages donors, and attracts volunteers. Campaigns are tailored to the Zimbabwean context." },
    ],
    keywords: [
      "NGO website Zimbabwe", "non-profit website design Zimbabwe",
      "charity website Harare", "donation website Zimbabwe",
      "NGO digital marketing Zimbabwe", "non-profit SEO Zimbabwe",
      "online donation system Zimbabwe", "community organization website Harare",
    ],
    metaTitle: "NGO & Non-profit Website Design Zimbabwe | KuWeX Studios",
    metaDescription: "Websites, online donation systems, and digital marketing for Zimbabwean NGOs and non-profits. Amplify your impact. From $1,500.",
  },
  {
    slug: "transport-logistics",
    name: "Transport & Logistics",
    shortName: "Transport",
    icon: "Truck",
    tagline: "Move goods, move online",
    description: "Websites and digital marketing for Zimbabwean transport companies, logistics providers, courier services, and freight forwarders.",
    heroTitle: "Digital Marketing for Transport & Logistics in Zimbabwe",
    heroSubtitle: "From courier services in Harare to cross-border freight companies — we build websites that attract shippers, streamline bookings, and build trust.",
    challenges: [
      { title: "Shippers can't find you", desc: "Businesses search \"courier service Harare\" or \"freight company Zimbabwe\" and you don't appear. You're losing contracts to competitors with websites." },
      { title: "No online booking", desc: "Customers call to book shipments. An online booking system would capture orders 24/7 and reduce phone workload." },
      { title: "No shipment tracking", desc: "Customers want to track their shipments online. A tracking portal builds trust and reduces status inquiry calls." },
      { title: "No service area visibility", desc: "Customers don't know your routes, coverage areas, and delivery zones. A website with route maps clarifies this instantly." },
    ],
    solutions: [
      { title: "Transport Company Websites", desc: "Professional websites showcasing your fleet, routes, services, coverage areas, and pricing. Built for B2B and B2C shippers." },
      { title: "Online Booking Systems", desc: "Customers book shipments online — select origin, destination, weight, and service level. Instant quotes and WhatsApp confirmation." },
      { title: "Shipment Tracking Portals", desc: "Customer portals where shippers track their deliveries in real-time, reducing status inquiry calls and building trust." },
      { title: "Transport SEO", desc: "Rank for \"courier service Zimbabwe\", \"freight company Harare\", \"logistics company Zimbabwe\" — keywords shippers search." },
    ],
    services: ["Web Design", "SEO Services", "Software Development", "WhatsApp Integration"],
    results: [
      { metric: "3x", label: "Online bookings" },
      { metric: "Page 1", label: "Ranking for transport keywords" },
      { metric: "50%", label: "Fewer status inquiry calls" },
      { metric: "24/7", label: "Booking availability" },
    ],
    faqs: [
      { q: "How much does a transport company website cost in Zimbabwe?", a: "A transport website costs $2,000-$8,000. Standard sites with services and routes start at $2,000. Sites with online booking, shipment tracking, and WhatsApp integration start at $5,000. KuWeX Studios builds logistics websites for the Zimbabwean market." },
      { q: "Can you build an online shipment booking system?", a: "Yes. We build online booking systems where customers select origin, destination, weight, and service level. The system generates instant quotes, accepts payment (Paynow/EcoCash/USD), and sends WhatsApp confirmation. Staff manage bookings via an admin dashboard." },
      { q: "Can you build a shipment tracking portal?", a: "Yes. We build customer tracking portals where shippers enter a tracking number and see real-time status updates. This reduces status inquiry calls by up to 50% and builds trust with B2B clients." },
      { q: "How do I rank my transport company on Google?", a: "Transport SEO requires: service-specific keywords (\"courier service Harare\", \"freight forwarding Zimbabwe\"), Google Business Profile, route/service pages, schema markup, and location-specific content. KuWeX Studios achieves Page 1 rankings within 3-6 months." },
    ],
    keywords: [
      "transport website Zimbabwe", "logistics website design Zimbabwe",
      "courier service website Harare", "freight company website Zimbabwe",
      "transport SEO Zimbabwe", "logistics digital marketing Harare",
      "shipment tracking website Zimbabwe", "cross-border transport website Zimbabwe",
    ],
    metaTitle: "Transport & Logistics Website Design Zimbabwe | KuWeX Studios",
    metaDescription: "Websites, booking systems, and tracking portals for Zimbabwean transport and logistics companies. From $2,000.",
  },
  {
    slug: "food-restaurant",
    name: "Food & Restaurant",
    shortName: "Food & Restaurant",
    icon: "UtensilsCrossed",
    tagline: "Fill more tables and orders",
    description: "Websites and digital marketing for Zimbabwean restaurants, food outlets, caterers, and food delivery services.",
    heroTitle: "Digital Marketing for Food & Restaurant Businesses in Zimbabwe",
    heroSubtitle: "From restaurants in Harare to food delivery services in Bulawayo — we build websites that showcase your menu, take online orders, and fill tables.",
    challenges: [
      { title: "No online menu", desc: "Customers search for your menu online and can't find it. They choose a competitor with a visible menu instead." },
      { title: "No online ordering", desc: "Customers want to order via WhatsApp or website. Without online ordering, you're losing sales to competitors who offer it." },
      { title: "No table reservations", desc: "Customers call to book tables and get no answer. Online reservation booking would capture diners 24/7." },
      { title: "Invisible on Google Maps", desc: "Tourists and locals search \"restaurants near me\" and you don't appear. Google Business Profile optimization is critical." },
    ],
    solutions: [
      { title: "Restaurant Websites", desc: "Beautiful websites with menu, photos, opening hours, location map, and online ordering or reservation functionality." },
      { title: "Online Ordering Systems", desc: "Customers browse your menu, add items to cart, and order via WhatsApp or website. Payment via EcoCash, Paynow, or cash on delivery." },
      { title: "Table Reservation Systems", desc: "Online booking system where diners select date, time, and party size. Automated WhatsApp confirmation reduces no-shows." },
      { title: "Food SEO & Google Maps", desc: "Rank on Google Maps for \"restaurants in Harare\", \"food delivery Zimbabwe\", \"best pizza Bulawayo\" — local search keywords." },
    ],
    services: ["Web Design", "SEO Services", "Social Media Marketing", "WhatsApp Integration"],
    results: [
      { metric: "3x", label: "Online orders" },
      { metric: "Page 1", label: "Google Maps ranking" },
      { metric: "60%", label: "Orders via WhatsApp" },
      { metric: "24/7", label: "Reservation availability" },
    ],
    faqs: [
      { q: "How much does a restaurant website cost in Zimbabwe?", a: "A restaurant website costs $1,500-$5,000. Basic sites with menu and photos start at $1,500. Sites with online ordering, table reservations, and WhatsApp integration start at $3,000. KuWeX Studios builds beautiful restaurant websites for the Zimbabwean market." },
      { q: "Can you build online ordering for my restaurant?", a: "Yes. We build online ordering systems where customers browse your menu, add items to cart, and place orders via WhatsApp or website. Payment options include EcoCash, Paynow, USD, or cash on delivery. Orders are sent directly to your kitchen via WhatsApp." },
      { q: "Can you add table reservations?", a: "Yes. We build online reservation systems where diners select date, time, party size, and special requests. Automated WhatsApp confirmation reduces no-shows. Staff can manage reservations via a simple dashboard." },
      { q: "How do I rank my restaurant on Google Maps in Zimbabwe?", a: "Restaurant local SEO requires: optimized Google Business Profile, photos, menu upload, opening hours, customer reviews, location-specific keywords, and a mobile-optimized website. KuWeX Studios optimizes your Google Maps presence to rank for \"restaurants near me\" searches." },
    ],
    keywords: [
      "restaurant website Zimbabwe", "food website design Harare",
      "online ordering system Zimbabwe", "restaurant menu website Zimbabwe",
      "food delivery website Zimbabwe", "restaurant SEO Harare",
      "catering website Zimbabwe", "cafe website design Zimbabwe",
    ],
    metaTitle: "Food & Restaurant Website Design Zimbabwe | KuWeX Studios",
    metaDescription: "Websites, online ordering, and table reservations for Zimbabwean restaurants and food businesses. From $1,500.",
  },
];
